DirtyBits/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('', include('Threshold.urls'))
]

Threshold/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from Threshold import views

urlpatterns = [
    path('', views.Index.as_view(), name = 'index'),
    #  path('problem/', include('views.problem'))
    path('contests', views.Contests.as_view(), name = 'contests'),
    path('contests/<int:pk>', login_required(views.Contest.as_view()), name = 'contest'),
    path('contests/<int:contest_id>/problem/<int:pk>', login_required(views.Problem.as_view()), name = 'Problem'),
    path('run/', views.RunCode, name = 'run')
    # path('contests/run/', views.redirect_view)
]

auth/urls.py
from django.urls import path

from auth import views

urlpatterns = [
    path('signup/', views.SignUp),
    path('login/', views.UserLogin),
    path('logout/', views.Logout)
]

Threshold/models.py
from django.db import models
from django.contrib.auth.models import User
import markdown2


class Problem(models.Model):
    difficulty_level = [
        ('1', 'easy'),
        ('2', 'medium'),
        ('3', 'hard')
    ]
    # part = [
    #     ('ll', 'Linked List'),
    #     ('q', 'Queue')
    # ]
    name = models.CharField(max_length = 50)
    description = models.TextField()
    level = models.CharField(max_length = 10, choices = difficulty_level)
    Input = models.TextField(max_length = 100)
    Output = models.TextField(max_length = 100)
    # topic = models.CharField(max_length = 100, choices = part)
    
    #computed property
    @property
    def description_html(self):
        return markdown2.markdown(self.description)

    def __str__(self):
        return self.name

class Contest(models.Model):
    name = models.CharField(max_length = 256)
    start_date = models.DateTimeField() #stores with time zone
    end_date = models.DateTimeField()
    description = models.TextField()
    is_private = models.BooleanField(default = False)
    Problems = models.ManyToManyField('Problem')

    def __str__(self):
        return self.name

class StudentContest(models.Model):
    contest = models.ForeignKey('Contest', on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    def __str__(self):
        return "{} - {}".format(self.user, self.contest)

class Submission(models.Model):
    LANGUAGES = [
        (1, 'cpp'),
        (2, 'c'),
        (3, 'java'),
        (4, 'python')
    ]
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    contest = models.ForeignKey('Contest', on_delete = models.CASCADE)
    problem = models.ForeignKey('Problem', on_delete = models.CASCADE)
    source = models.TextField()
    language = models.IntegerField(choices = LANGUAGES)
    score = models.IntegerField(null = True)
    createdAt = models.DateTimeField(auto_now_add = True) #stores the time when the entry is created

Threshold/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, TemplateView, ListView, CreateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseForbidden
import requests
from django.views.decorators.csrf import csrf_exempt
import json
from coderunner.coderunner import code


# Create your views here.

from Threshold import models


class Index(TemplateView):
    template_name = 'index.html'

# @login_required(login_url = '/auth/login')


class Contests(LoginRequiredMixin, ListView):
    login_url = 'auth/login/'
    redirect_field_name = 'redirected_to'
    model = models.Contest
    template_name = 'Threshold/contests.html'

# @login_required(login_url = '/auth/login')


class Contest(DetailView):
    model = models.Contest
    template_name = 'Threshold/contest.html'

# @login_required(login_url = '/auth/login')


class Problem(DetailView):
    template_name = 'Threshold/problem.html'

    def get_queryset(self):
        return models.Contest.objects.get(id=self.kwargs['contest_id']).Problems

@csrf_exempt
def redirect_view(request):
    # print("HELLO")
    response = redirect('run')
    return response


def RunCode(request):
    SourceCode = request.POST.get('source')
    Language = request.POST.get('lang')
    if(request.POST.get('input') != ''):
        input_data = request.POST.get('input')
        r = code(SourceCode, Language, inp = input_data, path = False)
        r.run()
    else:
        r = code(SourceCode, Language, path = False)
        r.run()
    cstat = r.getStatus()
    rstat = "Running"
    time = r.getTime()
    memory = r.getMemory()
    out = r.getOutput()
    if(cstat == "Accepted"):
        data = {
        'cstat' : cstat,
        'rstat' : rstat,
        'time' : time,
        'memory' : memory,
        'output' : out
        }
        return JsonResponse(data)

    else:
        err = r.getError()
        data = {
        'cstat' : cstat,
        'rstat' : rstat,
        'time' : time,
        'memory' : memory,
        'output' : out,
        'error' : err
        }
        print(data)
        return JsonResponse(data)

templates/Threshold/components/contest_card.html
<div class="card">
    <div class="card-body">
      <h5 class="card-title">{{contest.name}}</h5>
      <h6 class="card-subtitle mb-2 text-muted">{{contest.start_date}}</h6>
      <p class="card-text">{{contest.description}}</p>
      <a href="{% url 'contest' contest.id %}" class="card-link">Enter Contest</a>
    </div>
</div>

templates/Threshold/components/problem_card.html
<div class="card">
    <div class="card-body">
        <h5 class="card-title">{{ problem.name }}</h5>
        <p class="card-text">
            {% autoescape off %}
        {{problem.description_html}}
            {% endautoescape %}
        </p>
        <a href="{% url 'Problem' contest_id=contest.id pk=problem.id %}" class = 'card-link'> Attempt </a>
    </div>
</div>

templates/Threshold/contest.html
{% extends 'base.html' %}

{% block content %}

<div class="row pl-5">
    <h1>{{contest.name}}</h1>
</div>
<div class="row pl-5">
    <p>{{contest.start_date}} - {{contest.end_date}}</p>
    <hr>
    <p>{{contest.description}}</p>
    <hr>
</div>
<div class="row pt">
    {% for problem in contest.Problems.all %}
    <div class="col-4 pt-4">
        {% include 'Threshold/components/problem_card.html' %}
    </div>
    {% endfor %}
</div>
    

{% endblock %}

templates/Threshold/contests.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% for contest in contest_list %}
    <div class="col-4">
        {% include 'Threshold/components/contest_card.html' %}
    </div>
    {% endfor %}
</div>

{% endblock %}

templates/Threshold/problem.html
{% extends 'base.html' %}

{% block content %}

<div class="row pl-4">
    <h1>{{problem.name}}</h1>
</div>

<div class="row pl-4">
    <p>
        {% autoescape off %}
        {{problem.description_html}}
        {% endautoescape %}
    </p>
</div>

<div style="padding-left: 6%;">
    <p>
        <h3>Test Cases</h3>
    </p><hr>
    <p>
        <h4>Input</h4>
    </p><hr>
    <pre>
        {{ problem.Input }}
    </pre><hr>
    <p>
        <h4>Output</h4>
    </p><hr>
    <pre>
        {{ problem.Output }}
    </pre><hr>
</div>


<div>
    <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />

    <div class="container">
        <div id="topbar">
            <div class="lang-choose">
                <select class="form-control" name="lang" id="lang">
                    <option value="C">C (gcc 4.8.4)</option>
                    <option value="C++">C++ (g++ 4.8.4)</option>
                    <option value="C#">C# (mono 3.2.8)</option>
                    <option value="Go">Go (go 1.4.2)</option>
                    <option value="Haskell">Haskell (ghc 7.4.1)</option>
                    <option value="Java">Java (openjdk 1.7.0_09)</option>
                    <option value="JavaScript">JavaScript (Rhino 1.7)</option>
                    <option value="Common Lisp">Lisp (csc 4.8.0.5)</option>
                    <option value="Pascal">Pascal (fpc 2.6.2)</option>
                    <option value="PHP">PHP (php 5.5.9)</option>
                    <option value="Python2">Python (python 2.7.6)</option>
                    <option value="Python3" selected>Python (python 3)</option>
                    <option value="Ruby">Ruby (ruby 2.1.1)</option>
                    <option value="Rust">Rust (rustc 1.4.0)</option>
                    <option value="Plain Text">Text</option>
                </select>

            </div> 
            <div id="settings">
                <div class="theme-choose">
                    <select class="form-control" name="theme" id="theme">
                        <option value="Light" selected>Light</option>
                        <option value="Monokai">Monokai</option>
                        <option value="Solarised Light">Solarised Light</option>
                        <option value="Twilight">Twilight</option>
                    </select>
                </div> 
                <!-- <a class="" id="download">
                    download code
                    <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
                </a> -->
            </div>
        </div>
        
        <pre id="editor" style="height: 300px"></pre>

        <div id="editor-statusbar">
        </div>


        <div class="row">{% csrf_token %}
            <div id="showres">
                <div class="pull-left user-input-area">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="user-input"> Use custom input for testing your code
                        </label>
                    </div>
                </div>

                <div style="margin-left:85.4%;"class="run-save-panel">
                    <button class="btn btn-success" id="runcode"  data-toggle="tooltip" data-placement="top" title="Compile and Run">Compile and Run</button>
                </div>
            </div>
        </div> 

        <div class="row">
            <div class="input-container">
                <textarea id="custom-input" class="input-textarea" placeholder="Write inputs to program."></textarea>
            </div>
        </div> 
        <div class="outputbox">

            <div class="outputio">
                <div class="outputerror">
                    <div class="errorkey"></div>
                    <pre class="errormessage"></pre>
                </div>
                <div class="io-show">
                    <b>Output</b>
                    <pre class="output-text outputo"> </pre>
                    <b>Input</b>
                    <pre class="output-text outputi"> </pre>
                </div>
            </div>

            <div class="output-details">
                <div class="correct log-details">
                    <b>Log Details:</b>
                    <div id="demo"></div>
                    <script type="text/javascript">
                        var myDate = new Date();
                        var hours = myDate.getHours();
                        var minutes = myDate.getMinutes();
                        var ampm = hours >= 12 ? 'pm' : 'am';
                        hours = hours % 12;
                        hours = hours ? hours : 12;
                        minutes = minutes < 10 ? '0'+minutes : minutes;
                        var strTime = hours + ':' + minutes + ampm;
                        document.getElementById("demo").innerHTML = myDate.getDate()+"/"+(parseInt(myDate.getMonth())+1).toString()+"/"+myDate.getFullYear()+" at "+strTime;
                    </script>
                </div>
                <div class="correct time">
                    <b>Time (sec)</b>
                    <div class="value"></div>
                </div>
                <div class="correct memory">
                    <b>Memory (KB)</b>
                    <div class="value"></div>
                </div>
                <div class="correct runstat">
                    <b>Run Status</b>
                    <div class="value"></div>
                </div>
                <div class="correct compilestat">
                    <b>Compile Status</b>
                    <div class="value"></div>
                </div>
            </div>
        </div>
    </div> 

    <footer class="container">
        <span class="pull-right"> Copyright © 2019 Himanshu Dhiman</span>
    </footer>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'Threshold/css/my_css.css' %}" />
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <script src="{% static 'Threshold/js/my_js.js' %}"  charset="utf-8"></script>
  <script src="{% static 'Threshold/js/jquery.min.js' %}" charset="utf-8"></script>
  <script src="{% static 'ace-builds/src/ace.js' %}" charset="utf-8"></script>
  <script src="{% static 'ace-builds/src/ext-statusbar.js' %}" charset="utf-8"></script>
  <script src="{% static 'ace-builds/src/ext-language_tools.js' %}" charset="utf-8"></script>
  <title>Login</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand">DirtyBits</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{% url 'contests' %}">Contest</a>
        {% if request.user.is_authenticated %}
        Hello, {{ request.user.first_name }}
        <a class="nav-item nav-link mr-sm-2" href="/auth/logout">Logout</a>
        {% else %}
        <a class="nav-item nav-link mr-sm-2" href="/auth/login">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>
  {% block content %} {% endblock %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="justify-content-center">
        <h1>Welcome to DirtyBits</h1>
    </div>

{% endblock %}